### ISSUE TITLE
Does the ground truth contain information about instance ID?

### ISSUE THREAD

**Issue by BaiLiping** [utiasASRL/pyboreas#16]
Hi, thanks for the dataset. I am working on 3D Multiobject tracking so for my project, instance ID is quite important. Please advice if the ground truth of this dataset contains this piece of information? Thanks

**Comment by keenan-burnett** [comment]
Yes it does. The ground truth text files contain a column called "UUID" which are persistent track IDs across individual scenes.

**Comment by BaiLiping** [comment]
Got it. Thanks a lot for your reply and dateset. Looking forward to validating our tracking alg with it.
