### ISSUE TITLE
3D Object Detection in Adverse Conditions?

### ISSUE THREAD

**Issue by MartinHahner** [utiasASRL/pyboreas#22]
Hi @keenan-burnett, great dataset! 🎉

Are you planning to release 3D Object Detection labels also for sequences containing rain and snowfall?
In your paper you _e.g._ mention Boreas-Objects-**V1**, so will there be a planned **V2** release?

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/14181188/160645326-bebfca9b-c1c6-4a0d-83b8-fd9e05e0b5a2.png">

**Comment by keenan-burnett** [comment]
Hi Martin!

We're looking into this internally. Since we already have the data, it wouldn't be too much extra work to label some frames from the rain or snow sequences. I can't promise that there will be a V2 with these additions, but I'll say it could happen over the next year.

**Comment by meiiqi** [comment]
Hi @keenan-burnett, any recent updates on this?  Thanks!

**Comment by keenan-burnett** [comment]
Hi @meiiqi, we have plenty of interesting data taken during adverse weather but I currently don't have enough budget allocated for another Scale data annotation run. I know there are some researchers at my institute who are interested in pursuing this towards their winter autonomous driving research but it won't be happening any time soon.
