### ISSUE TITLE
Where to download the 3d detection label

### ISSUE THREAD

**Issue by ShenZheng2000** [utiasASRL/pyboreas#43]
I cannot find where to download the 3D label here: https://www.boreas.utias.utoronto.ca/#/download. 

Could you please provide me with the link?

**Comment by keenan-burnett** [comment]
Have you seen this?

https://github.com/utiasASRL/pyboreas/blob/master/download.md

**Comment by ShenZheng2000** [comment]
Thanks. Got it.
