### ISSUE TITLE
Please check splits carefully

### ISSUE THREAD

**Issue by cppcute-pm** [utiasASRL/pyboreas#46]
Very appreciated for the excellent work related to Boreas dataset!
When I use the dataset dev-sdk, I found that the loc_train split in pyboreas.data.splits has a repeated sequence "boreas-2021-04-20-14-11" which occurred twice. This will infuence the sequence num in datasets and futher misleading the get_seq_from_ID's results.At the same time I found the "boreas-2021-04-22-15-00" sequence in odom_train only have the "imu_raw.csv" and "dmi.csv" files, which makes it not a training kind of sequence.
Above of all, I want you to fix these problems in this project and check the splits carefully, and thanks for the contribution to the community !
Best wishes !

**Comment by keenan-burnett** [comment]
Fixed
