### ISSUE TITLE
Applanix POSLV IMU specification

### ISSUE THREAD

**Issue by paaraujo** [utiasASRL/pyboreas#53]
Hi @keenan-burnett ,

Do you know which IMU is inside the Applanix? I was looking for any estimation of the bias instability and noise density of the accelerometers and gyroscopes, but I couldn't find any.

Thank you.

**Comment by keenan-burnett** [comment]
I don't have that information, sorry. All I know is that we have the Applanix POS LV 220 with "IMU-42". Their documentation doesn't provide any additional information about the IMU.
