### ISSUE TITLE
GPS coordinates

### ISSUE THREAD

**Issue by ed-cho** [utiasASRL/pyboreas#56]
Hi, I've realised that all GPS coordinates (latitude, longitude) in the gps_post_process.csv files seem to be somewhere around 0.764, -1.387, which is somewhere in the middle of the ocean. Once you plot them however, the trajectory looks just like the ones described in the website. I assume that these coordinates must have their reference coordinate, and describes how far away they are from that point. Can I ask where the origin might be please?

**Comment by keenan-burnett** [comment]
They're in radians.
