### ISSUE TITLE
Something about benchmarks

### ISSUE THREAD

**Issue by yangsc4063** [utiasASRL/pyboreas#57]
If I want to do pure radar object detection, the test results will be in the radar coordinate system and published with radar timestamps. How can I test it on the benchmark? 
Thank you for your work, looking forward to your reply.

**Comment by keenan-burnett** [comment]
Can you try transforming your detections into the nearest lidar frame and evaluating that way?

**Comment by keenan-burnett** [comment]
Try running `pyboreas/eval/detection.py` on a validation set locally with `--radar True` and see what results you get. The website benchmark uses the same format as this script.

**Comment by yangsc4063** [comment]
> Try running `pyboreas/eval/detection.py` on a validation set locally with `--radar True` and see what results you get. The website benchmark uses the same format as this script.

Thank you for your reply. I am just planning to do such a job now, but it has not been realized yet. I will try it later. Thank you again!
